import { chmodSync, mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { berthHome } from '../paths'

/**
 * Ensure a `berth` launcher in <berthHome>/bin and return that dir (to prepend to a spawned agent's
 * PATH). The launcher re-invokes the CURRENT runtime as Node against the CLI entry, so it works whether
 * Berth runs as the packaged Electron app (ELECTRON_RUN_AS_NODE) or plain node (the var is ignored there).
 */
export function ensureAgentBerthShim(cliEntry: string): string {
  const binDir = join(berthHome(), 'bin')
  mkdirSync(binDir, { recursive: true })
  const shimPath = join(binDir, 'berth')
  const body =
    '#!/bin/sh\n' +
    '# Auto-generated by Berth — launches the bundled CLI against the running server.\n' +
    `ELECTRON_RUN_AS_NODE=1 exec ${JSON.stringify(process.execPath)} ${JSON.stringify(cliEntry)} "$@"\n`
  if (!existsSync(shimPath) || readFileSync(shimPath, 'utf8') !== body) {
    writeFileSync(shimPath, body); chmodSync(shimPath, 0o755)
  }
  return binDir
}
